/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#ffffff",
        "outline": "#71717a",
        "surface-bright": "#18181b",
        "tertiary-fixed-dim": "#e4e4e7",
        "surface-dim": "#09090b",
        "on-surface": "#ffffff",
        "primary-fixed": "#ffffff",
        "tertiary-container": "#27272a",
        "surface-container": "#18181b",
        "on-secondary-fixed-variant": "#a1a1aa",
        "on-primary-container": "#ffffff",
        "on-tertiary-fixed": "#000000",
        "secondary-container": "#27272a",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#f4f4f5",
        "on-primary-fixed-variant": "#d4d4d8",
        "secondary": "#a1a1aa",
        "surface-container-high": "#27272a",
        "on-tertiary": "#ffffff",
        "outline-variant": "#3f3f46",
        "surface": "#09090b",
        "surface-tint": "#ffffff",
        "on-tertiary-fixed-variant": "#71717a",
        "secondary-fixed-dim": "#a1a1aa",
        "surface-variant": "#18181b",
        "primary": "#ffffff",
        "inverse-surface": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-container": "#ffffff",
        "background": "#000000",
        "error": "#ef4444",
        "on-secondary-fixed": "#000000",
        "surface-container-lowest": "#000000",
        "surface-container-highest": "#27272a",
        "surface-container-low": "#09090b",
        "primary-container": "#ffffff",
        "error-container": "#7f1d1d",
        "on-background": "#ffffff",
        "on-tertiary-container": "#ffffff",
        "on-surface-variant": "#a1a1aa",
        "on-primary": "#000000",
        "on-primary-fixed": "#000000",
        "inverse-on-surface": "#000000",
        "on-error-container": "#fca5a5",
        "tertiary-fixed": "#ffffff",
        "primary-fixed-dim": "#e4e4e7",
        "tertiary": "#ffffff",
        
        // Strict Black & White theme palette mapping
        "bg-base": "#000000",
        "surface-level-1": "#09090b",
        "surface-level-2": "#18181b",
        "border-subtle": "#27272a",
        "border-hover": "#3f3f46",
        "accent-primary": "#ffffff",

        // Login / Auth Pages specific
        "custom-bg": "#000000",
        "custom-surface": "#09090b",
        "custom-border": "#27272a",
        "custom-primary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.375rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "lg": "24px",
        "md": "16px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "sm": "8px",
        "xl": "40px",
        "xs": "4px",
        "2xl": "64px",
        "container-max": "1440px"
      },
      fontFamily: {
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "display-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "code-md": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      },
      backgroundImage: {
        'grid-pattern': "url(\"data:image/svg+xml,%3Csvg width='40' height='40' viewBox='0 0 40 40' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M0 0h40v40H0V0zm39 39V1H1v38h38z' fill='%23ffffff' fill-opacity='0.03' fill-rule='evenodd'/%3E%3C/svg%3E\")",
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
